# -*- coding: utf-8 -*-
"""Contact.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nK8W47EN0vJQvEjYZeR7nF0E4TMdLOOF
"""

import json  # Importing JSON module to handle reading/writing data

# Function to create a new contact
def new_contact():
    name = input("Enter Name: ")
    contact = input("Enter Contact: ")
    email = input("Enter Email: ")

    # Using consistent lowercase keys
    person = {"name": name, "contact": contact, "email": email}
    return person

# Function to display contacts
def view_contact(people):
    for i, person in enumerate(people):
        print(i + 1, "|", person["name"], "|", person["contact"], "|", person["email"])

# Function to delete a contact
def delete_contact(people):
    view_contact(people)

    while True:
        number = input("Enter the number of the contact you want to delete: ")
        try:
            number = int(number)
            if number <= 0 or number > len(people):
                print("Invalid number, try again.")
            else:
                break
        except:
            print("Invalid number.")

    people.pop(number - 1)
    print("Contact deleted")

# Function to search contacts
def search(people):
    search_name = input("Search for who? ").lower()
    results = []

    for person in people:
        if search_name in person["name"].lower():
            results.append(person)

    if results:
        view_contact(results)
    else:
        print("Contact not found")

# Start of the program
print("Hi, welcome to Contact Manager System")

# Load contacts from file, or start with empty list if file is missing or empty
try:
    with open("contacts.json", "r") as f:
        people = json.load(f)["contacts"]
except (FileNotFoundError, json.JSONDecodeError):
    people = []

# Main program loop
while True:
    print("\nContact Size:", len(people))
    command = input("You can 'Add', 'Delete' or 'Search' and 'Q' for quit: ").lower()

    if command == "add":
        person = new_contact()
        people.append(person)
        print("Contact Added")
    elif command == "delete":
        if people:
            delete_contact(people)
        else:
            print("No contacts to delete.")
    elif command == "search":
        if people:
            search(people)
        else:
            print("No contacts to search.")
    elif command == "q":
        break
    else:
        print("Invalid command, try again")

# Save contacts to file
with open("contacts.json", "w") as f:
    json.dump({"contacts": people}, f, indent=2)

print("Goodbye! Your contacts have been saved.")