# -*- coding: utf-8 -*-
"""Python1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nK8W47EN0vJQvEjYZeR7nF0E4TMdLOOF
"""

import sys

name = input("What is your name? ")
start = input("Hello " + name + ", are you ready to play?").lower()
if start == "y" or start == "yes":
  print("Lets Play!")

  boat = input("Do you want a boat? (yes/no) ").lower()
  swim = input("Can you swim? (yes/no) ").lower()
  direction = input("Would you want to take a left or a right?").lower()
  if direction == "right":
    choice = input("You have reached a fork in the road, one leads into a river, the other a forest. River or forest?").lower()
    if choice == "river":
      if (boat == "yes" and swim == "yes") or (boat == "yes" and swim == "no"):
        print("You can use your boat! You've reached the castle on the other side!\n")
        print("You encounter WUMPUS, he can only be defeated through his fear of being understood like most people today\n")
        print("Answer the following question to counter his fear of being seen: \n")
        answer = input("To protect what is the purpose of WUMPUS' life?").lower()
        if answer == "gold":
          print("Oh no, WUMPUS has ghosted you! the gold is all yours")
        else:
          print("Yep- you're ded.")
          sys.exit()
      elif (boat == "no" and swim == "yes"):
        print("You can't swim through a river and you don't have a boat, you've drowned!")
        sys.exit()
      else:
        print("You are incapable of crossing the river. Why would you come here?!")
        sys.exit()
    else:
      print("The forest? 0 survival instincts, lol you're out")
      sys.exit()
  else:
    print("You left, you're out.")
    sys.exit()
else:
  print("Why are you here?")

